### ISSUE TITLE
Refactoring `count`

### ISSUE THREAD

**Issue by harlessmark** [harlessmark/totally-random#28]
```js
boolean(count = 1) {
    if (count < 1) throw new Error("count must be greater than 0");

    const arr = [];

    for (let i = 0; i < count; i++) {
      const oneOrTwo = this.to(2);

      if (oneOrTwo === 1) {
        arr.push(true);
      } else arr.push(false);
    }

    return count === 1 ? arr[0] : arr;
  }
```

I found a neat way to remove a lot of duplicate code. It creates an array no matter what the value of `count` is. In the `return` statement you'll see how it handles what to output. Need this in all of the other methods that take `count` as an argument.

**Comment by Gridonyx** [comment]
I'll knock this out while handling #29

**Comment by superhackerboy** [comment]
@Gridonyx is this done?

**Comment by Gridonyx** [comment]
Yep, all of them use the ternary for the return. `shuffle` and `string` don't currently have the option for returning an array so those don't have it of course. Those two are on the todo list though.

**Comment by superhackerboy** [comment]
Ok I'll close this whenever that's complete. Just make mention of it in the PR

**Comment by superhackerboy** [comment]
ETA on this? I don't mind taking a stab at it if you're too busy

**Comment by Gridonyx** [comment]
I've been on vacation this week which is why I haven't worked on it haha, I'll be getting back home this weekend
